version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: We_Work
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: administrateur
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/We_Work
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: administrateur
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

volumes:
  postgres_data: