version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: We_Work
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: administrateur
    ports:
      - "5432:5432"
    networks:
      - wework-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/We_Work
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=administrateur
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wework-network

networks:
  wework-network:
    driver: bridge

volumes:
  postgres_data: